import PhotosUI
import SwiftUI

struct PhotoCreateView:View {
    @Environment(AppModel.self) private var model;@Environment(\.dismiss) private var dismiss
    @State private var pickerItem:PhotosPickerItem?;@State private var prepared:PreparedPhoto?;@State private var cropImage:UIImage?;@State private var cameraImage:UIImage?;@State private var showCamera=false;@State private var cameraFailure:PhotoGenerationFailure?;@State private var style:PhotoColoringStyle = .classic;@State private var background:PhotoBackgroundMode = .simplify;@State private var editor:ColoringProject?
    init(initialPrepared: PreparedPhoto? = nil, initialOptions: PhotoGenerationOptions = .init(style: .classic, background: .simplify)) {
        _prepared = State(initialValue: initialPrepared)
        _style = State(initialValue: initialOptions.style)
        _background = State(initialValue: initialOptions.background)
    }
    private var completed:PhotoGenerationRecord?{if case .completed(let id)=model.photoPhase{return model.photoHistory.first{$0.id==id}};return nil}
    var body:some View{NavigationStack{ScrollView{VStack(alignment:.leading,spacing:22){Text("PHOTO STUDIO").font(.caption.bold()).tracking(1.4).foregroundStyle(Color.artCoral);Text("Photo to coloring page").font(.largeTitle.bold());Text("Choose a bright photo with one clear subject. Your local preview is re-encoded without photo metadata.").foregroundStyle(.secondary);if let result=completed{resultView(result)}else if let prepared{form(prepared)}else{acquisition};status}.padding(20).frame(maxWidth:700).frame(maxWidth:.infinity)}.background(Color.artPaper).toolbar{ToolbarItem(placement:.topBarLeading){Button("Close"){dismiss()}}}}
    .onChange(of:pickerItem){_,item in guard let item else{return};Task{do{guard let data=try await item.loadTransferable(type:Data.self)else{throw PhotoGenerationFailure.corrupt};let p=try PhotoImagePreparationService.prepare(data:data,source:.photoLibrary);try? FileManager.default.removeItem(atPath:p.path);cropImage=p.image}catch{cameraFailure=(error as? PhotoGenerationFailure) ?? .unknown}}}
    .sheet(isPresented:$showCamera){NativeCameraPicker{cameraImage=$0}}
    .sheet(item:$cropImage){image in SquareCropView(image:image){cropped in do{prepared=try PhotoImagePreparationService.storeComposition(cropped,source:cameraImage == nil ? .photoLibrary:.camera);cropImage=nil;cameraImage=nil}catch{cameraFailure=(error as? PhotoGenerationFailure) ?? .unknown}}}
    .alert("Use this photo?",isPresented:Binding(get:{cameraImage != nil},set:{if !$0{cameraImage=nil}})){Button("Retake"){cameraImage=nil;showCamera=true};Button("Use Photo"){cropImage=cameraImage}}message:{Text("Review your capture before positioning it.")}
    .alert(item:$cameraFailure){failure in Alert(title:Text("Photo unavailable"),message:Text(failure.message),primaryButton:failure == .cameraDenied ? .default(Text("Open Settings")){UIApplication.shared.open(URL(string:UIApplication.openSettingsURLString)!)}:.default(Text("OK")),secondaryButton:.cancel())}
    .fullScreenCover(item:$editor){project in if let page=model.page(id:project.pageID){EditorLoaderView(page:page,project:project)}}}
    private var acquisition:some View{VStack(spacing:14){PhotosPicker(selection:$pickerItem,matching:.images){PhotoActionLabel(title:"Choose from Photos",symbol:"photo.on.rectangle.angled",color:Color.artLavender)};Button{Task{switch await CameraAuthorization.request(){case .success:showCamera=true;case .failure(let e):cameraFailure=e}}}label:{PhotoActionLabel(title:"Take Photo",symbol:"camera.fill",color:Color.artCoral)}.buttonStyle(.plain)}.padding(.vertical,20)}
    private func form(_ photo:PreparedPhoto)->some View{VStack(alignment:.leading,spacing:18){Image(uiImage:photo.preview).resizable().scaledToFill().aspectRatio(1,contentMode:.fit).frame(maxWidth:.infinity).clipped().clipShape(RoundedRectangle(cornerRadius:24));Text("Coloring style").font(.headline);Picker("Style",selection:$style){ForEach(PhotoColoringStyle.allCases){Text($0.rawValue).tag($0)}}.pickerStyle(.segmented);Text("Background").font(.headline);Picker("Background",selection:$background){ForEach(PhotoBackgroundMode.allCases){Text($0.rawValue).tag($0)}}.pickerStyle(.segmented);Button{model.generatePhoto(prepared:photo,options:.init(style:style,background:background))}label:{Label("Make Coloring Page", systemImage: "sparkles").font(.headline).frame(maxWidth:.infinity).padding().foregroundStyle(.white).background(Color.artInk,in:Capsule())}.disabled(model.photoPhase.isBusy);Button("Choose Another Photo"){prepared=nil;pickerItem=nil;model.resetPhotoGeneration()}.frame(maxWidth:.infinity)}.buttonStyle(PressScaleStyle())}
    @ViewBuilder private var status:some View{switch model.photoPhase{case .uploading:message("Checking your photo creation allowance…");case .processing:message("Drawing color-ready shapes…");case .cleaning:message("Cleaning every outline…");case .failed(.limitReached):limitReached;case .failed(let e):VStack{Text(e.message).foregroundStyle(.secondary);Button("Try Again"){model.resetPhotoGeneration()}.buttonStyle(.bordered)};default:EmptyView()}}
    private var limitReached:some View{VStack(alignment:.leading,spacing:14){Label("Photo allowance reached",systemImage:"clock.badge.exclamationmark").font(.title3.bold());Text(model.subscriptions.access.hasPremium ? "You’ve used this month’s photo coloring page allowance. You can create again after your monthly reset." : "You’ve used your free photo creations. Unlock Premium for a larger monthly photo allowance.").foregroundStyle(.secondary);if !model.subscriptions.access.hasPremium{Button("Unlock Premium"){dismiss();Task{try? await Task.sleep(for:.milliseconds(350));model.presentPaywall(context:"Photo coloring pages")}}.buttonStyle(.borderedProminent).tint(Color.artCoral)};Button("Explore Coloring Pages"){model.selectedTab=1;dismiss()}.buttonStyle(.bordered);Button("Not now"){dismiss()}.font(.subheadline).foregroundStyle(.secondary)}.padding(18).frame(maxWidth:.infinity,alignment:.leading).background(Color.aiCream.opacity(0.7),in:RoundedRectangle(cornerRadius:22))}
    private func message(_ text:String)->some View{Label(text,systemImage:"sparkles").font(.headline).padding().frame(maxWidth:.infinity).background(Color.artMint.opacity(0.3),in:RoundedRectangle(cornerRadius:18))}
    private func resultView(_ record:PhotoGenerationRecord)->some View{VStack(spacing:18){if let image=model.photoImage(for:record,thumbnail:false){Image(uiImage:image).resizable().scaledToFit().background(.white).clipShape(RoundedRectangle(cornerRadius:24))};Text("Your coloring page is ready").font(.title2.bold());Button{editor=model.makeProject(for:record.page)}label:{Label("Start Coloring",systemImage:"paintbrush.fill").frame(maxWidth:.infinity).padding().background(Color.artInk,in:Capsule()).foregroundStyle(.white)};Button("Try Again with This Photo"){prepared=model.restorePrepared(record);style=record.options.style;background=record.options.background;model.resetPhotoGeneration()};Button("Choose Another Photo"){prepared=nil;model.resetPhotoGeneration()}}.buttonStyle(PressScaleStyle())}
}
extension UIImage: @retroactive Identifiable { public var id:ObjectIdentifier{ObjectIdentifier(self)} }
